config/routes.rb
LastAssignment::Application.routes.draw do
 

  get "catagory/Online"
  get "catagory/Offline"
  get "catagory/Mobile"
  get "catagory/Newfeed"
  get "catagory/blank"
  devise_for :users, :controllers => {:registrations => "registrations"} 

  resources :comments
  resources :users

  resources :forums do
    resources :categoros
    resources :topics do
      member do
        post 'upvote'
      end
    end
  end
  get 'topics/haha'
  get '/forums/:forum_id/topics/:id/commentreply' ,to: "topics#commentreply", as: 'commentreply_forum_topic'
  post '/forums/:forum_id/topics/:id/commentreply', to: 'topics#save_commentreply', as: 'save_commentreply_forum_topic'

  root 'forums#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics, :dependent => :destroy
	has_many :categoros, :dependent => :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
    render :layout => false
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @online = Topic.where("cate_type = ?", "Game Online").paginate(:page => params[:page],:per_page => 2,:order => "created_at DESC")
    @offline = Topic.where("cate_type = ?", "Game Offline").paginate(:page => params[:page],:per_page => 2,:order => "created_at DESC")
    @mobile = Topic.where("cate_type = ?", "Game Mobile").paginate(:page => params[:page],:per_page => 2,:order => "created_at DESC")
    @newfeed = Topic.where("cate_type = ?", "New Feed").paginate(:page => params[:page],:per_page => 2,:order => "created_at DESC")
  end

  # GET /forums/new
  def new
    @forum = Forum.new
    render :layout => false
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    @blank = catagory_blank_path
    respond_to do |format|
      if @forum.save
        format.html { redirect_to @blank, notice: 'Forum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @forum }
      else
        format.html { render action: 'new' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= stylesheet_link_tag "bootstrap-custom" %>
<div class="container">
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title%><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :as => "Create Forum", :class => "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<%= stylesheet_link_tag "bootstrap-custom" %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<table class="table">
  <% @forums.each do |forum| %>
  <tr>
    <td align="center"><%= image_tag('rails_forum.jpg', :class => 'featurette-image img-responsive', :style => 'align:center;')%><br><%=link_to 'Click here to enter '+ forum.title + ' FORUM', forum, :class => "btn btn-danger", :style => "color:white;width:500px; font-size: 24px"%>
    </td>
  </tr>
  <%end%>
</table>
</div>
<%if current_user.Admin? %>
<div class="container">
  <% @forums.each do |forum| %>
  <div class="row">
    <div class="col-sm-6 col-md-4">
          <div class="thumbnail" style="height:310px;" align="center">
            <%= image_tag('GAME.png', :class => 'featurette-image img-responsive')%>
            <div class="caption">
              <p><%=link_to forum.title, forum, :style => "font-size: 24px"%></p>
              <p><%= link_to 'Edit', edit_forum_path(forum), :class => "btn btn-primary" %>
                <%= link_to 'Destroy', forum, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            </p>
            </div>
          </div>
        </div>
    <div class="col-sm-10 col-md-8">
      <div class="thumbnail" style="height:310px;">
        <%= pie_chart Topic.group(:cate_type).count %>
      </div>
    </div>
  </div>
  <%end%>

  <button class="btn btn-info" href="#" role="button"><%= link_to 'Manage User', users_path, :style => "color:white" %></button>
  <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Forum
  </button>
<%end%>   

  <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Topic</h4>
      </div>
      <div class="modal-body">
        <object type="text/html" width="100%" height="500px" data="<%= new_forum_path %>"> </object>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onClick="window.location.reload()">Close</button>
      </div>
    </div>
  </div>
</div>
    <!-- div Modal -->  

</div>
  <div class="container">    
    <footer>
        <!-- Button trigger modal -->
        <p>&copy; Company 2014</p>
    </footer>
  </div>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

app/views/forums/show.html.erb
<div class="container" style="margin-bottom: 20px; margin-top: 20px;">
  <!-- Static navbar -->
  <div class="navbar navbar-inverse " role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Rails Forums', forums_path, :class => 'navbar-brand' %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to 'Home', @forum %></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>                
              </ul>
            </div>
          </div>
        </div>
</div>
    <div class="container" >
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-2" align="center">
          <div class="list-group">
            <a href="<%=catagory_Online_path%>" class="list-group-item active"><h3 class="panel-title">Game Online</h3></a><br>
            <a href="<%=catagory_Offline_path%>" class="list-group-item active"><h3 class="panel-title">Game Offline</h3></a><br>
            <a href="<%=catagory_Offline_path%>" class="list-group-item active"><h3 class="panel-title">Game Mobile</h3></a><br>
            <a href="<%=catagory_Newfeed_path%>" class="list-group-item active"><h3 class="panel-title">News Feed</h3></a><br>
          </div>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>

        <div class="col-md-8">
          <div class="panel panel-primary">
            <!-- Default panel contents -->
              <div class="panel-heading"><h3 class="panel-title">Game Online</h3></div>
            <!-- Table -->
            <%@count_cmt = 0%>
            <table class="table">
              <tbody>
                <% @online.each do |topic| %>
                  <tr class="<%= cycle('list_line_odd','list_line_even')%>">
                    <td>
                      <%= image_tag(topic.img_head, :style => "width:100px; height:60px")%>
                    </td>
                    <td class="list_description" >
                      <dl>
                        <dt><%=link_to topic.title, forum_topic_path(:forum_id => @forum, :id => topic) %></dt>
                        <dd><%= truncate(strip_tags(topic.description),:length => 80) %></dd>
                      </dl>
                    </td>
                    <td class="list_actions" >
                      <p>Last Reply By: <%=topic.user_name%>, <%= topic.comments.last.created_at %></p>
                      <p>Number of Reply: <%=topic.comments.count-1%></p>
                      <%@count_cmt += (topic.comments.count-1)%>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
            <div class="flickr_pagination">
              <%=will_paginate @online, :inner_window => 1, :outer_window =>0, :container => false %>
            </div>
          </div>

          <div class="panel panel-primary">
            <!-- Default panel contents -->
              <div class="panel-heading"><h3 class="panel-title">Game Offline</h3></div>
            <!-- Table -->
            <table class="table">
              <tbody>
                <% @offline.each do |topic| %>
                  <tr class="<%= cycle('list_line_odd','list_line_even')%>">
                    <td>
                      <%= image_tag(topic.img_head, :style => "width:100px; height:60px")%>
                    </td>
                    <td class="list_description" >
                      <dl>
                        <dt><%=link_to topic.title, forum_topic_path(:forum_id => @forum, :id => topic) %></dt>
                        <dd><%= truncate(strip_tags(topic.description),:length => 80) %></dd>
                      </dl>
                    </td>
                    <td class="list_actions" >
                      <p>Last Reply By: <%=topic.user_name%>, <%= topic.comments.last.created_at %></p>
                      <p>Number of Reply: <%=topic.comments.count-1%></p>
                      <%@count_cmt += (topic.comments.count-1)%>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
            <div class="flickr_pagination">
              <%=will_paginate @offline, :inner_window => 1, :outer_window =>0 , :container => false%>
            </div>
          </div>

          <div class="panel panel-primary">
            <!-- Default panel contents -->
              <div class="panel-heading"><h3 class="panel-title">Game Mobile</h3></div>
            <!-- Table -->
            <table class="table">
              <tbody>
                <% @mobile.each do |topic| %>
                  <tr class="<%= cycle('list_line_odd','list_line_even')%>">
                    <td>
                      <%= image_tag(topic.img_head, :style => "width:100px; height:60px")%>
                    </td>
                    <td class="list_description" >
                      <dl>
                        <dt><%=link_to topic.title, forum_topic_path(:forum_id => @forum, :id => topic) %></dt>
                        <dd><%= truncate(strip_tags(topic.description),:length => 80) %></dd>
                      </dl>
                    </td>
                    <td class="list_actions" >
                      <p>Last Reply By: <%=topic.user_name%>, <%= topic.comments.last.created_at %></p>
                      <p>Number of Reply: <%=topic.comments.count-1%></p>
                      <%@count_cmt += (topic.comments.count-1)%>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
            <div class="flickr_pagination">
              <%=will_paginate @mobile, :inner_window => 1, :outer_window =>0 , :container => false%>
            </div>
          </div>

          <div class="panel panel-primary">
            <!-- Default panel contents -->
              <div class="panel-heading"><h3 class="panel-title">New Feed</h3></div>
              
              

            <!-- Table -->
            <table class="table">
              <tbody>
                <% @newfeed.each do |topic| %>
                  <tr class="<%= cycle('list_line_odd','list_line_even')%>">
                    <td>
                      <%= image_tag(topic.img_head, :style => "width:60px; height:60px")%>
                    </td>
                    <td class="list_description" >
                      <dl>
                        <dt><%=link_to topic.title, forum_topic_path(:forum_id => @forum, :id => topic) %></dt>
                        <dd><%= truncate(strip_tags(topic.description),:length => 80) %></dd>
                      </dl>
                    </td>
                    <td class="list_actions" >
                      <p>Last Reply By: <%=topic.user_name%>, <%= topic.comments.last.created_at %></p>
                      <p>Number of Reply: <%=topic.comments.count-1%></p>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
            <div class="flickr_pagination">
              <%=will_paginate @newfeed, :inner_window => 1, :outer_window =>0 , :container => false%>
            </div>
          </div>

    <button class="btn btn-default" data-toggle="modal" data-target="#myModal">
      Post New Topic
    </button>

<!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">New Topic</h4>
          </div>
          <div class="modal-body">
            <object type="text/html" width="100%" height="500px" data="<%= new_forum_topic_url(@forum) %>" > </object>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onClick="window.location.reload()">Close</button>
          </div>
        </div>
      </div>
    </div>

       </div>

        <div class="col-md-2">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title" align="center">Forum Statistics</h3>
            </div>
            <div class="panel-body">
              <h5><em>Topics: <%=@forum.topics.count%></em></h5>
              <h5><em>Replies: <%=@count_cmt%></em></h5>
              <h5><em>Member: <% @user = User.find(:all)%><%=@user.count%></em></h5>
            </div>
          </div>

          <h2>Advertisment</h2>
          <%= image_tag("QC.jpg", alt: "Rails",) %></br>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>

      </div>
      
    </div> <!-- /container -->