config/routes.rb
LastAssignment::Application.routes.draw do
 

  get "catagory/Online"
  get "catagory/Offline"
  get "catagory/Mobile"
  get "catagory/Newfeed"
  get "catagory/blank"
  devise_for :users, :controllers => {:registrations => "registrations"} 

  resources :comments
  resources :users

  resources :forums do
    resources :categoros
    resources :topics do
      member do
        post 'upvote'
      end
    end
  end
  get 'topics/haha'
  get '/forums/:forum_id/topics/:id/commentreply' ,to: "topics#commentreply", as: 'commentreply_forum_topic'
  post '/forums/:forum_id/topics/:id/commentreply', to: 'topics#save_commentreply', as: 'save_commentreply_forum_topic'

  root 'forums#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	validates_presence_of :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @topic = Topic.find(params[:topic_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :topic_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-primary">
    <div class="panel-heading" >
    <h3 class="panel-title" style="display:inline"><%= comment.user_name %> said:</h3>
    <p class="" style="display:inline; font-size: 12px; margin-left:450px;">Reply at <%= comment.cmt_date%></p>
    </div>              
    <div class="panel-body" style="font-size: 20px;">
        <%= comment.body %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@forum_topic, @forum_topic.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit :as => "Create comment"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Topic</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.topic_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @comment.topic_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>