config/routes.rb
LastAssignment::Application.routes.draw do
 

  get "catagory/Online"
  get "catagory/Offline"
  get "catagory/Mobile"
  get "catagory/Newfeed"
  get "catagory/blank"
  devise_for :users, :controllers => {:registrations => "registrations"} 

  resources :comments
  resources :users

  resources :forums do
    resources :categoros
    resources :topics do
      member do
        post 'upvote'
      end
    end
  end
  get 'topics/haha'
  get '/forums/:forum_id/topics/:id/commentreply' ,to: "topics#commentreply", as: 'commentreply_forum_topic'
  post '/forums/:forum_id/topics/:id/commentreply', to: 'topics#save_commentreply', as: 'save_commentreply_forum_topic'

  root 'forums#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	belongs_to :forum
	has_many :comments, :dependent => :destroy
	has_many :votes, :dependent => :destroy
	validates_presence_of :title
	validates_length_of :title, :maximum=>50

	def self.Game(type)
		Topic.where("cate_type = ?", type)
	end
end	

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :load_forum

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @topic }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @topic }
    end
  end
  def haha
  end
  # GET /topics/new
  def new
    @topic = Topic.new
    @comment = @topic.comments.build

    render :layout => false
  end

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to forum_topic_path(:forum_id => @forum, :id => @topic)
  end

  def commentreply
    @topic = Topic.find(params[:id])
    @comment = @topic.comments.build
    @time = Time.new

    render :layout => false
  end

  def save_commentreply
    params.permit!
    if Topic.exists?(params[:id])
      @topic = Topic.find(params[:id])
      @comment = @topic.comments.build(params[:comment])
      @comment.user_name = current_user.name
      @comment.user_id = current_user.id
      @comment.cmt_date = @time.inspect
    else
      redirect_to(forums_path, :notice =>"Please specify a valid Forum")
    end
    @blank = catagory_blank_path
     respond_to do |format|
      if @comment.save
        format.html { redirect_to @blank, :notice => 'Your reply was posted'}
      else
        format.html { render :action => "new" }
      end
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    params.permit!
    @topic = Topic.new(topic_params)
    @time = Time.new
    @comment = @topic.comments.build(params[:comment])
    @comment.user_name = current_user.name
    @comment.cmt_date = @time.inspect
    @topic.topic_date = @time.inspect
    @topic.user_name = current_user.name
    @topic.forum = @forum

    respond_to do |format|
      if @topic.save
        format.html { redirect_to forum_topic_path(:forum_id => @forum, :id => @topic), notice: 'Topic was successfully created.' }
        format.json { render inline: "location.reload();" }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to forum_topic_path(:forum_id => @forum, :id => @topic), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    @topic.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def load_forum
        if Forum.exists?(params[:forum_id])
          @forum = Forum.find(params[:forum_id]);
        end
        unless @forum
          redirect_to(forums_path, :notice =>"Please specify a valid Forum")
        end     
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :forum_id, :comment_id, :cate_type, :description, :img_head, :img_body, :img_footer, :link)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_commentreply_form.html.erb
<%= stylesheet_link_tag "bootstrap-custom" %>
<div class="container">
<%= form_for(@comment, :url => commentreply_forum_topic_url(:forum_id=>@forum, :id=>@topic)) do |f| %>
	<% if @comment.errors.any? %>
	<div id="error_explanation">
		 <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this commentreply from being saved:</h2>

		 <ul>
		 <% @comment.error.full_messages.each do |msg|%>
		 	<li><%= msg %></li>
      	<% end %>
      	</ul>
    </div>
  <% end %>
  	 <div class="field">
		<%= f.label :body %><br />
		<%= f.text_area(:body, :size => "50x10")%>
	</div>
    <p><br></p>
	 <div class="actions">
		<%= f.submit :as => "Create Reply", :class => "btn btn-primary"%>
	</div>
<% end %>
</div>

app/views/topics/_form.html.erb
<%= stylesheet_link_tag "bootstrap-custom" %>
<div class="container" style="margin-top: 20px">
<%= form_for(@topic, :url => forum_topics_path) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :Category %><br> 
    <%= f.select :cate_type, [ 'Game Online', 'Game Offline', 'Game Mobile', 'New Feed' ], :prompt => 'Select One' %>
  </div>
  <div class="field">
    <%= f.label "Images to post Screenshot" %><br>
    <%= f.file_field :img_head, :class =>'btn btn-default', :placeholder => "img_head" %>
    <%= f.file_field :img_body, :class =>'btn btn-default', :placeholder => "img_body" %>
    <%= f.file_field :img_footer, :class =>'btn btn-default', :placeholder => "img_footer" %>
  </div>
  <div clas="field">
      <%= f.label "Video" %><br>
      <%= f.text_field :link %>
  </div>
  <div clas="field">
      <%= f.label :description %><br>
      <%= f.text_area(:description, :size => "60x10")%>
  </div>
  <%= fields_for(@comment) do |cf| %>
    <div clas="field">
        <%= cf.label "Requirement" %><br />
        <%= cf.text_area(:body, :size => "60x10")%>
    </div>
  <% end %>
  <br>
  <div class="actions">
  <%= f.submit :as => "Create Topic", :class => "btn btn-primary"%>
</div>
<% end %>
</div> <!-- End container -->

app/views/topics/commentreply.html.erb
<div class="container">

	<h3 id="page_title" style="margin-left:10px">Reply To <%= @topic.title %></h3>	 
	<%= render 'commentreply_form' %>
 
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Forum</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= pluralize(topic.votes.count, "vote") %></td>
        <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
        <td><%= topic.forum_id %></td>
        <td><%= topic.comment_id %></td>
        <td><%= link_to 'Show', forum_topic_path(:forum_id => @forum, :id => topic) %></td>
        <td><%= link_to 'Destroy', forum_topic_path(:forum_id => @forum, :id => topic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_forum_topic_path %>

app/views/topics/new.html.erb
<div class="container">

<h1 id="page_title" style="margin-left:10px">Create New topic</h1>
<%= render 'form' %>
</div>

app/views/topics/show.html.erb
<div class="container" style="margin-bottom: 20px; margin-top: 20px;">
  <!-- Static navbar -->
  <div class="navbar navbar-inverse " role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Rails Forums', forums_path, :class => 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', @forum %></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>          
        </ul>
      </div>
    </div>
  </div>
</div>
    


<div class="container">
  <div class="panel panel-info" style="background: url('styles/default/xenforo/gradients/category-23px-light.png') repeat-x scroll center top #FFFFFF">
    <div class="panel-heading">
      <h3 class="panel-title" font-size="24px" align="center"><%= @topic.title %></h3>
    </div>

    <div class="panel-body">
      <%= image_tag(@topic.img_head, :alt => "Dragons-and-titans-bandeau", :style => "width:900px; height:500px") %>
      <%=sanitize @topic.description %>
      <%= image_tag('Trailer_371x137.jpg', :alt => "img_body") %><br>
      <div align="center"><span style="font-size: medium"><iframe src="<%=@topic.link%>" allowfullscreen="" frameborder="0" height="300" width="500"></iframe></span></div>
      <%= image_tag('Screenshot_456x137.jpg', :alt => "img_body") %><br>
      <%= image_tag(@topic.img_body, :alt => "img_body", :style => "width:900px; height:500px") %><br>
      <%= image_tag(@topic.img_footer, :alt => "img_footer", :style => "width:900px; height:500px") %><br>
      <%= image_tag('System-req_480x137.jpg', :alt => "img_body") %><br>
      <div class="panel panel-danger" style="background: url('styles/default/xenforo/gradients/category-23px-light.png') repeat-x scroll center top #FFF4E5;">
        <div class="panel-body">
          <%=sanitize @topic.comments.find(@topic.id).body%>
        </div>
      </div>
      <%= image_tag('Download_480x137.jpg', :alt => "img_body") %><br>
      <div align="center" font-size="20px;">
        <%=image_tag('downloadmd.gif', :alt => "[Fshare] Borderlands Game of the Year", :style => "display: inline;")%>
        <a href="https://www.google.com.vn/?gfe_rd=cr&ei=AgIKVKDVDeGJ8Qf54ICIBQ&gws_rd=ssl#q=find+link+yourself+%2B+good+luck" target="_blank" class="internalLink"><b style="font-size: initial;">Download Here</b></a>
      </div>

      <p style="padding-top: 10px; margin-bottom:-10px;">Create at <%= @topic.created_at.to_date%> By <%= @topic.user_name%></p>
      <div class="#" style="padding-top: 10px">
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <%= pluralize(@topic.votes.count, "vote") %>
          <%= button_to '+1', upvote_forum_topic_path(:forum_id => @forum, :id => @topic), method: :post %>
        </div>
    </div>
  </div>
</div>


  <div class="detailBox" style="background: url('styles/default/xenforo/gradients/category-23px-light.png') repeat-x scroll center top #FFF4E5;">
    <div class="commentBox">
        
        <p class="taskDescription">Display <%=@topic.comments.count%> comments</p>
    </div>
    <div class="actionBox">
        <ul class="commentList">
          <% @topic.comments.each do |comment| %>
            <% if comment.id != @topic.id%>
            <%@u = User.find(comment.user_id)%>
            <li>
              <div class="commenterImage">
                  <%if @u.avatar?%>
                    <%= image_tag(@u.avatar,:class => 'img-circle')%>
                  <%else%>
                    <%= image_tag('no-avatar.jpg',:class => 'img-circle')%>img-circle
                  <%end%>
                  <h5><%=link_to comment.user_name, @u%><h5>
                </div>
                <div class="commentText">
                    <p class=""><p><strong><%=comment.user_name%></strong> said: </p>
                    <p><%=sanitize comment.body%></p></p> <span class="date sub-text"><%= comment.created_at.to_date%></span>

                </div>
            </li>
            <%end%>
            <%end%>
        </ul>
    </div>
  </div>
  <br>
  <button class="btn btn-primary" data-toggle="modal" data-target="#Reply" style="margin-left:15px;">
    Reply
  </button>
</div>



<% if current_user.Admin == true %>
  <div class="col-md-1" style="">
    <div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title" style="margin-left:-6px;"><%= link_to 'Destroy', forum_topic_path(:forum_id => @forum, :id => @topic), method: :delete, data: { confirm: 'Are you sure?' } %></h3>
          </div>
  </div>
<%end%>

    

<!-- Modal -->
<div class="modal fade" id="Reply" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Left Your Reply</h4>
      </div>
      <div class="modal-body">
        <object type="text/html" width="100%" height="400px" data="<%= commentreply_forum_topic_url(:forum_id=>@forum, :id=>@topic)%>"> </object>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onClick="window.location.reload()">Close</button>
      </div>
    </div>
  </div>
</div>
<div style = 'position:fixed; right:0; top:100px;' id = 'gotop'><%=image_tag('Up-Arrow-Icon.jpg', width: '50px', height: '50px')%></div>

app/views/topics/untitled.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<% root_path %>">
        RUBY ON RAILS HOANG TRAINING
          </a>
        </div>
      </div>
    </div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1 style="text-align: center">Welcome to Game Forum</h1>
        <%= image_tag("topic.jpg", alt: "Rails",) %>
    </div>